/*Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

来源：力扣（LeetCode）
链接：https://leetcode-cn.com/problems/find-the-difference
著作权归领扣网络所有。商业转载请联系官方授权，非商业转载请注明出处。*/

class Solution {
public:
    char findTheDifference(string s, string t) {
        vector<int> letter(26,0);
        for(int i = 0; i < s.size();++i){
            letter[s[i]-'a']++;
        }

        for(int i = 0; i < t.size();++i){
            letter[t[i]-'a']--;
            if(letter[t[i]-'a']==-1)
                return t[i];
        }
        return 'a';
    }
};

